# Use official PostgreSQL image from Docker Hub
FROM postgres:16

# Set environment variables for PostgreSQL (optional, override at runtime)
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydb

# Expose PostgreSQL port
EXPOSE 5432


